### ISSUE TITLE
1.1.4 is not tagged in this repository

### ISSUE THREAD

**Issue by gotmax23** [hpe-storage/nimble-ansible-modules#59]
`antsibull-build validate-tags` (antsibull-build is the build tool for the ansible community package) has determined that hpe.nimble 1.1.4 is not tagged in https://github.com/hpe-storage/nimble-ansible-modules. Please tag that release in this repository. See [Collection Requirements § Repository Management](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#repository-management) for more information on collection release tagging requirements. Thanks!

**Comment by gotmax23** [comment]
@ar-india and @datamattsson, can you please take a look at this? You're listed as the contacts for this collection.

**Comment by datamattsson** [comment]
Fixed https://github.com/hpe-storage/nimble-ansible-modules/releases/tag/v1.1.4
